[package]
name = "vrb_authent"
edition = "2024"
description = "Library for authorization functions."
keywords = ["vrb_authent", "authorization"]
version.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
utoipa = { workspace = true }
vrb_common = { workspace = true }
vrb_db = { workspace = true }
vrb_dbase = { workspace = true }
vrb_tools = { workspace = true }

[features]
# default = ["test", "mockdata"]
test=[]
mockdata = []
