[package]
name = "vrb_app"
edition = "2024"
description = "Library for assembling a binary file."
keywords = ["vrb_app"]
version.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "verbena"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
actix-cors = { workspace = true }
actix-files = { workspace = true }
actix-multipart = { workspace = true }
actix-web = { workspace = true }
dotenv = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true }
utoipa-redoc = { workspace = true }
utoipa-rapidoc = { workspace = true }
vrb_authent = { workspace = true }
vrb_chats = { workspace = true }
vrb_common = { workspace = true }
vrb_db = { workspace = true }
vrb_dbase = { workspace = true }
vrb_profiles = { workspace = true }
vrb_streams = { workspace = true }
vrb_tools = { workspace = true }

[features]
# default = ["test", "mockdata"]
test=[]
mockdata = []

