[package]
name = "vrb_profiles"
edition = "2024"
description = "Library for working with the 'profile' entity (user)."
keywords = ["vrb_profiles"]
version.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
actix-multipart = { workspace = true }
actix-web = { workspace = true }
chrono = { workspace = true }
diesel = { workspace = true }
log = { workspace = true }
mime = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
utoipa = { workspace = true }
vrb_authent = { workspace = true }
vrb_common = { workspace = true }
vrb_db = { workspace = true }
vrb_tools = { workspace = true }

[features]
default = ["test", "mockdata"]
test=[]
mockdata = []

[dev-dependencies]
# To test a web form with data and a file.
actix-multipart-test = "0.0.3"
vrb_authent = { version = "0.5", path="../vrb_authent", features = ["mockdata"] }

